### ISSUE TITLE
v1.2.2 tests fail agains MongoDB server 3.0.0-rc7 (already fixed in master)

### ISSUE THREAD

**Issue by triccardi-systran** [vsivsi/gridfs-locks#3]
When running npm up-to-date gridfs-locks tests (v1.2.2) against MongoDB server 3.0.0-rc7, it fails:
```
  68 passing (1m)
  2 failing

  1) gridfs-locks lock expiration should allow a read request to proceed when a prior write request dies without releasing write_req:
     Error: timeout of 5000ms exceeded
    at [object Object].<anonymous> (/home/riccardi/tmp/nodejs/test/node_modules/gridfs-locking-stream/node_modules/gridfs-locks/node_modules/mocha/lib/runnable.js:159:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
  

  2) gridfs-locks lock expiration should allow a read request to proceed when a prior write request dies waiting for a write lock without releasing write_req:
     Error: timeout of 5000ms exceeded
    at [object Object].<anonymous> (/home/riccardi/tmp/nodejs/test/node_modules/gridfs-locking-stream/node_modules/gridfs-locks/node_modules/mocha/lib/runnable.js:159:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
 
```

When applying commit add3224beb8605f74c5b3273bdd74148458b9dfd, all the tests pass.

Could you please release master to npm, and upgrade gridfs-locks-stream dependency constraint?

**Comment by vsivsi** [comment]
Hi, thanks for submitting this.  I'm currently working on issues gridfs-locks is having when using the new node mongo driver 2.0.x combined with the older server versions 2.4.x.  This combination is a hard requirement, so it's my highest priority to resolve these issues and get a new version on npm to resolve these issues.

I haven't done any testing yet with mongodb 3.0, and that is currently a low priority for me, but if the current `master` solves your issue, I'll look into quickly releasing just those changes to npm today.

**Comment by vsivsi** [comment]
I just published version 1.2.3 to npm.  Please let me know if this solves your issue.  -V

**Comment by vsivsi** [comment]
Hi, Now I see why using mongodb 3.0 triggered this issue for you.  The code was erroneously following the mongodb 2.4 code path in this case, rather than the more efficient mongodb 2.6 code.  I've updated the version check to handle mongodb 3.0.  I'll be publishing this momentarily as version 1.2.4 to npm

**Comment by triccardi-systran** [comment]
Hi,
I confirm that the tests pass on 1.2.3 and on 1.2.2 + c63a6224407ac71cb1bfbe87615d20d681835eba on MongoDB server 3.0.0-rc7.

Thanks.

**Comment by vsivsi** [comment]
Great, thanks for confirming.  FYI, I'm going to publish v1.3.0 this afternoon, which contains support for using version 2.x of the mongodb node.js native driver.  It will continue to support use of the older 1.4 native driver as well.
